name: CI
on: push


jobs:
  black:
    name: Black formatted
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v1
       with:
         python-version: 3.7
     - name: Check all Python files
       run: |
         pip install black
         git ls-files | grep '\.py$' | xargs black
         git diff --color=always --exit-code

  install:
    name: Install as rez package (Py${{ matrix.python_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [2.7, 3.7]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - uses: j0yu/setup-rez@v1

      # cpdf-binaries
      - uses: actions/checkout@v2
      - run: rez build --install
      - run: rez env cpdf -- which cpdf